#!/bin/sh
set -e

case "${1}" in
	prereqs)
		exit 0
		;;
esac

modprobe efivarfs
mount -t efivarfs efivars /sys/firmware/efi/efivars

if [ ! -e /sys/firmware/efi/efivars/dasboot-d719b2cb-3d3a-4596-a3bc-dad00e67656f ]; then
    mkdir /newroot
    mount -o bind /root/chroot /newroot
    mount -o move /newroot /root
fi

exit 0
